# Generated by Django 2.1.15 on 2019-12-11 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelsrelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('cardno', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'card',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'person',
            },
        ),
        migrations.AddField(
            model_name='card',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='modelsrelapp.Person'),
        ),
    ]
