# Generated by Django 2.1.15 on 2019-12-11 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelsrelapp', '0003_auto_20191211_1619'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
