# Generated by Django 2.1.15 on 2019-12-16 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelsrelapp', '0005_auto_20191211_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=5)),
                ('salary', models.FloatField()),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modelsrelapp.Emp')),
            ],
            options={
                'db_table': 'emp',
            },
        ),
    ]
