# Generated by Django 2.1.15 on 2019-12-16 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelsrelapp', '0006_emp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=5)),
                ('manager', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='modelsrelapp.Spy')),
            ],
            options={
                'db_table': 'spies',
            },
        ),
    ]
