# Generated by Django 2.1.15 on 2019-12-16 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelsrelapp', '0007_spy'),
    ]

    operations = [
        migrations.CreateModel(
            name='relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'relation',
            },
        ),
        migrations.CreateModel(
            name='Weiuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'weiuser',
            },
        ),
        migrations.AddField(
            model_name='relation',
            name='fans',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follwed_user', to='modelsrelapp.Weiuser'),
        ),
        migrations.AddField(
            model_name='relation',
            name='follwed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fanns_user', to='modelsrelapp.Weiuser'),
        ),
    ]
