# Generated by Django 2.1.15 on 2019-12-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelsrelapp', '0008_auto_20191216_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='built_time',
            field=models.DateField(null=True),
        ),
    ]
